const levels = [
    {
        id: 1,
        name: "Hutan Ajaib",
        description: "Mulai petualangan di hutan yang penuh rahasia.",
        difficulty: "Pemula",
        timer: 60,
        bg: "assets/bg.png",
        words: [
            { word: "RUSA", hint: "Hewan bertanduk di hutan" },
            { word: "AKAR", hint: "Bagian tumbuhan di dalam tanah" },
            { word: "DAUN", hint: "Bagian tumbuhan berwarna hijau" },
            { word: "MADU", hint: "Cairan manis dari lebah" },
            { word: "BATU", hint: "Benda keras di sungai" },
            { word: "POHON", hint: "Tumbuhan besar berkayu" },
            { word: "SEMAK", hint: "Tumbuhan perdu rendah" },
            { word: "BUNGA", hint: "Bagian cantik tanaman" },
            { word: "BURUNG", hint: "Hewan bersayap yang terbang" },
            { word: "ULAR", hint: "Hewan melata panjang" },
            { word: "SUNGAI", hint: "Aliran air alami yang besar" },
            { word: "BUKIT", hint: "Tanah yang lebih tinggi" },
            { word: "JAMUR", hint: "Tumbuha berbentuk payung" },
            { word: "RANTING", hint: "Cabang kecil pohon" },
            { word: "TANAH", hint: "Pijakan tempat tumbuh tanaman" }
        ]
    },
    {
        id: 2,
        name: "Kota Misteri",
        description: "Pecahkan teka-teki di kota berkabut.",
        difficulty: "Menengah",
        timer: 45,
        bg: "assets/bg_city.png",
        words: [
            { word: "JALAN", hint: "Tempat kendaraan melintas" },
            { word: "PASAR", hint: "Tempat jual beli barang" },
            { word: "HOTEL", hint: "Tempat menginap sementara" },
            { word: "TAMAN", hint: "Area hijau di tengah kota" },
            { word: "POLISI", hint: "Penegak hukum" },
            { word: "GEDUNG", hint: "Bangunan tinggi bertingkat" },
            { word: "MACET", hint: "Kondisi jalan penuh kendaraan" },
            { word: "LAMPU", hint: "Penerang jalan di malam hari" },
            { word: "TOKO", hint: "Tempat membeli kebutuhan" },
            { word: "KANTOR", hint: "Tempat orang bekerja" },
            { word: "BUS", hint: "Kendaraan umum besar" },
            { word: "TROTOAR", hint: "Jalur pejalan kaki" },
            { word: "PABRIK", hint: "Tempat produksi barang" },
            { word: "POLUSI", hint: "Pencemaran udara kota" },
            { word: "STASIUN", hint: "Tempat pemberhentian kereta" }
        ]
    },
    {
        id: 3,
        name: "Laut Dalam",
        description: "Selami lautan dan temukan harta karun.",
        difficulty: "Lanjut",
        timer: 40,
        bg: "assets/bg_ocean.png",
        words: [
            { word: "OMBAK", hint: "Gerakan air laut yang bergulung" },
            { word: "PENYU", hint: "Hewan laut yang membawa rumahnya" },
            { word: "KARANG", hint: "Rumah bagi ikan-ikan kecil" },
            { word: "GARAM", hint: "Bumbu dapur dari air laut" },
            { word: "BADAI", hint: "Cuaca buruk di lautan" },
            { word: "HIU", hint: "Ikan predator bergigi tajam" },
            { word: "PAUS", hint: "Mamalia laut terbesar" },
            { word: "GURITA", hint: "Hewan laut berkaki delapan" },
            { word: "KERANG", hint: "Hewan lunak bercangkang keras" },
            { word: "PASIR", hint: "Butiran halus di pantai" },
            { word: "KEPITING", hint: "Hewan bercapit" },
            { word: "UBUR", hint: "Hewan lunak transparan menyengat" },
            { word: "SELAM", hint: "Aktivitas berenang di bawah air" },
            { word: "PERAHU", hint: "Kendaraan air kecil" },
            { word: "LAYAR", hint: "Kain penangkap angin di kapal" }
        ]
    },
    {
        id: 4,
        name: "Luar Angkasa",
        description: "Jelajahi bintang dan planet asing!",
        difficulty: "Ahli",
        timer: 30,
        bg: "assets/bg_space.png",
        words: [
            { word: "PLANET", hint: "Benda langit yang mengelilingi matahari" },
            { word: "ROKET", hint: "Kendaraan menuju angkasa" },
            { word: "KOMET", hint: "Bintang berekor" },
            { word: "ALIEN", hint: "Makhluk asing luar bumi" },
            { word: "SATELIT", hint: "Benda yang mengorbit planet" },
            { word: "ASTRONOT", hint: "Penjelajah antariksa" },
            { word: "BINTANG", hint: "Benda langit yang memancarkan cahaya" },
            { word: "MATAHARI", hint: "Pusat tata surya kita" },
            { word: "BULAN", hint: "Satelit alami bumi" },
            { word: "GALAKSI", hint: "Kumpulan milyaran bintang" },
            { word: "METEOR", hint: "Batu luar angkasa yang jatuh" },
            { word: "GRAVITASI", hint: "Gaya tarik antar benda" },
            { word: "ORBIT", hint: "Jalur lintasan planet" },
            { word: "TELESKOP", hint: "Alat melihat bintang jauh" },
            { word: "GERHANA", hint: "Fenomena tertutupnya benda langit" },
            { word: "NEBULA", hint: "Awan debu kosmik" }
        ]
    },
    {
        id: 5,
        name: "Dunia Sains",
        description: "Laboratorium pengetahuan yang rumit.",
        difficulty: "Master",
        timer: 25,
        bg: "assets/bg.png",
        words: [
            { word: "MIKROSKOP", hint: "Alat untuk melihat benda super kecil" },
            { word: "FOTOSINTESIS", hint: "Proses tumbuhan memasak makanan" },
            { word: "GRAVITASI", hint: "Gaya tarik bumi" },
            { word: "LABORATORIUM", hint: "Tempat penelitian ilmiah dilakukan" },
            { word: "TERMOMETER", hint: "Alat pengukur suhu tubuh" },
            { word: "EKSPERIMEN", hint: "Percobaan untuk membuktikan teori" },
            { word: "BAKTERI", hint: "Organisme mikroskopis penyebab penyakit" },
            { word: "VIRUS", hint: "Agen infeksi super kecil" },
            { word: "ATOM", hint: "Bagian terkecil dari materi" },
            { word: "MOLEKUL", hint: "Gabungan dua atom atau lebih" },
            { word: "ENERGI", hint: "Kemampuan melakukan usaha" },
            { word: "REAKSI", hint: "Perubahan kimiawi zat" },
            { word: "BIOLOGI", hint: "Ilmu tentang makhluk hidup" },
            { word: "FISIKA", hint: "Ilmu tentang alam dan energi" },
            { word: "KIMIA", hint: "Ilmu tentang susunan zat" },
            { word: "LISTRIK", hint: "Energi dari aliran elektron" }
        ]
    },
    {
        id: 6,
        name: "Mega Tantangan",
        description: "Ujian terakhir. Kata-kata terpanjang dan tersulit!",
        difficulty: "Dewa",
        timer: 20, // Increased slighty for fairness on phone
        bg: "assets/bg_space.png",
        words: [
            { word: "TANGGUNGJAWAB", hint: "Kewajiban menanggung segala sesuatu" },
            { word: "MEMPERTANGGUNGJAWABKAN", hint: "Memberikan penjelasan atas perbuatan" },
            { word: "KEANEKARAGAMAN", hint: "Hal yang bermacam-macam jenisnya" },
            { word: "BERKESINAMBUNGAN", hint: "Terus menerus tanpa henti" },
            { word: "KETIDAKADILAN", hint: "Sikap tidak memihak yang benar" },
            { word: "PENGETAHUAN", hint: "Segala sesuatu yang diketahui" },
            { word: "KEBIJAKSANAAN", hint: "Kepandaian menggunakan akal budi" },
            { word: "PERMUSYAWARATAN", hint: "Perundingan untuk mufakat" },
            { word: "PERIKEMANUSIAAN", hint: "Sifat cinta kasih sesama manusia" },
            { word: "KESEJAHTERAAN", hint: "Kondisi aman sentosa dan makmur" },
            { word: "PENDIDIKAN", hint: "Proses pengubahan sikap dan tata laku" },
            { word: "KEBUDAYAAN", hint: "Hasil cipta, rasa, dan karsa manusia" },
            { word: "PEMBANGUNAN", hint: "Proses, cara, perbuatan membangun" },
            { word: "PERSAUDARAAN", hint: "Ikatan pertemanan seperti saudara" },
            { word: "KEKELUARGAAN", hint: "Semangat seperti dalam keluarga" },
            { word: "NASIONALISME", hint: "Paham kebangsaan" }
        ]
    }
];
